### ISSUE TITLE
项目名称的三种风格

### ISSUE THREAD

**Issue by lightyears1998** [dangoyears/Database-CourseDesign#1]
我在URL和Readme看见了两个名字“db-course_design”和“DatabaseCourseDesign”。其中包含脊柱、下划线和驼峰三种风格。这是有意为之吗？

(×_×）

**Comment by DangoSky** [comment]
这是因为vue-cli创建的项目名称不让用大写的，而且我觉得数据库是一个前导，所以个人喜好上就用了-，而课程设计是一个整体，就按常规的用了_（驼峰和下划线我都用，就看是用在变量名还是函数之类的）ORZ。
